<template>
  <div>
    <!-- <blockquote
      class="tiktok-embed"
      cite="https://www.tiktok.com/@bdvn.vietnampost/video/7226346307705720070"
      data-video-id="7226346307705720070"
      style="max-width: 605px; min-width: 325px"
    >
      <section>
        <a
          target="_blank"
          title="@bdvn.vietnampost"
          href="https://www.tiktok.com/@bdvn.vietnampost?refer=embed"
          >@bdvn.vietnampost</a
        >
        Người phụ nữ nhỏ nhắn, chân chất lại thật thà nhưng đã dám bước ra khỏi
        “vùng an toàn” của bản thân để học hỏi, mang lại nguồn năng lượng tích
        cực và giá trị tốt đẹp đến những người xung quanh! Chúc chị Thắm nhiều
        sức khoẻ, luôn “máu lửa” với nghề và công tác tốt! Chị chính là nguồn
        cảm hứng để chúng tôi tiếp tục phấn đấu, cố gắng từng ngày! ❤️
        <a
          title="capcut"
          target="_blank"
          href="https://www.tiktok.com/tag/capcut?refer=embed"
          >#CapCut</a
        >
        <a
          title="tíchcực"
          target="_blank"
          href="https://www.tiktok.com/tag/t%C3%ADchc%E1%BB%B1c?refer=embed"
          >#tíchcực</a
        >
        <a
          title="năng_lượng_tích_cực"
          target="_blank"
          href="https://www.tiktok.com/tag/n%C4%83ng_l%C6%B0%E1%BB%A3ng_t%C3%ADch_c%E1%BB%B1c?refer=embed"
          >#năng_lượng_tích_cực</a
        >
        <a
          title="buudienvietnam"
          target="_blank"
          href="https://www.tiktok.com/tag/buudienvietnam?refer=embed"
          >#buudienvietnam</a
        >
        <a
          title="vietnampost"
          target="_blank"
          href="https://www.tiktok.com/tag/vietnampost?refer=embed"
          >#vietnampost</a
        >
        <a
          title="vnpost"
          target="_blank"
          href="https://www.tiktok.com/tag/vnpost?refer=embed"
          >#vnpost</a
        >
        <a
          title="nguoibuudien"
          target="_blank"
          href="https://www.tiktok.com/tag/nguoibuudien?refer=embed"
          >#nguoibuudien</a
        >
        <a
          title="nguoibuudienlamgi"
          target="_blank"
          href="https://www.tiktok.com/tag/nguoibuudienlamgi?refer=embed"
          >#nguoibuudienlamgi</a
        >
        <a
          title="trend"
          target="_blank"
          href="https://www.tiktok.com/tag/trend?refer=embed"
          >#trend</a
        >
        <a
          title="xh"
          target="_blank"
          href="https://www.tiktok.com/tag/xh?refer=embed"
          >#xh</a
        >
        <a
          title="xuhuong"
          target="_blank"
          href="https://www.tiktok.com/tag/xuhuong?refer=embed"
          >#xuhuong</a
        >
        <a
          title="viral"
          target="_blank"
          href="https://www.tiktok.com/tag/viral?refer=embed"
          >#viral</a
        >
        <a
          title="fypシ゚viral"
          target="_blank"
          href="https://www.tiktok.com/tag/fyp%E3%82%B7%E3%82%9Aviral?refer=embed"
          >#fypシ゚viral</a
        >
        <a
          title="foryou"
          target="_blank"
          href="https://www.tiktok.com/tag/foryou?refer=embed"
          >#foryou</a
        >
        <a
          title="fypシ"
          target="_blank"
          href="https://www.tiktok.com/tag/fyp%E3%82%B7?refer=embed"
          >#fypシ</a
        >
        <a
          title="xuhuong"
          target="_blank"
          href="https://www.tiktok.com/tag/xuhuong?refer=embed"
          >#xuhuong</a
        >
        <a
          title="xuhuong2023"
          target="_blank"
          href="https://www.tiktok.com/tag/xuhuong2023?refer=embed"
          >#xuhuong2023</a
        >
        <a
          target="_blank"
          title="♬ nhạc nền  - Bưu Điện Việt Nam"
          href="https://www.tiktok.com/music/nhạc-nền-Bưu-Điện-Việt-Nam-7226346442285271814?refer=embed"
          >♬ nhạc nền - Bưu Điện Việt Nam</a
        >
      </section>
    </blockquote>
    <script async src="https://www.tiktok.com/embed.js"></script> -->
  </div>
</template>
